language: d

sudo: false

os:
  - linux

d:
  - dmd-beta
  - dmd
  - dmd-2.076.0
  - ldc-beta
  - ldc
  - ldc-1.8.0
  - ldc-1.6.0
  - gdc

matrix:
  allow_failures:
      - d: gdc
      - d: dmd-beta
      - d: ldc-beta

script:
    - ./tests/run.sh
